### ISSUE TITLE
Create a converter which does just a few inlines at a time, for large files.

### ISSUE THREAD

**Issue by musiczhzhao** [trhallam/segysak-t21-tutorial#3]
Hi,

We noticed that there is a TODO item in _openzgy.py to create a converter which does just a few inlines at a time for large files. Do we have a estimation when this can be done?

Best,
Zhao

**Comment by trhallam** [comment]
Moving to main repository for `segysak`.

https://github.com/trhallam/segysak/issues/105#issue-1124104767
